[project]
name = "windows-theme-switcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "inquirerpy>=0.3.4",
    "json5>=0.12.1",
    "rich>=14.1.0",
]
